package com.nullplaying.limdo

internal fun SpokenCue.demonstrationStrokeIndex(characterStart: Int): Int? {
    if (characterStart < 0) return null

    when (this) {
        SpokenCue.RETRY_START,
        SpokenCue.RETRY_DIRECTION,
        SpokenCue.RETRY_FIRST_DOWN_DIRECTION,
        SpokenCue.RETRY_GUIDE,
        SpokenCue.RETRY_FINISH,
        -> return 0
        SpokenCue.RETRY_SECOND_START,
        SpokenCue.RETRY_SECOND_DIRECTION,
        SpokenCue.RETRY_SECOND_RIGHT_DIRECTION,
        SpokenCue.RETRY_SECOND_LEFT_DIRECTION,
        SpokenCue.RETRY_SECOND_GUIDE,
        SpokenCue.RETRY_SECOND_FINISH,
        -> return 1
        SpokenCue.RETRY_THIRD_START,
        SpokenCue.RETRY_THIRD_DIRECTION,
        SpokenCue.RETRY_THIRD_DOWN_DIRECTION,
        SpokenCue.RETRY_THIRD_GUIDE,
        SpokenCue.RETRY_THIRD_FINISH,
        -> return 2
        SpokenCue.RETRY_FOURTH_START,
        SpokenCue.RETRY_FOURTH_RIGHT_DIRECTION,
        SpokenCue.RETRY_FOURTH_GUIDE,
        SpokenCue.RETRY_FOURTH_FINISH,
        -> return 3
        SpokenCue.MENU_CONSONANTS,
        SpokenCue.MENU_VOWELS,
        SpokenCue.MENU_GANADA,
        SpokenCue.SUCCESS,
        SpokenCue.SUCCESS_A,
        SpokenCue.SUCCESS_AE,
        SpokenCue.SUCCESS_GIEOK,
        SpokenCue.SUCCESS_NIEUN,
        SpokenCue.SUCCESS_DIGEUT,
        SpokenCue.SUCCESS_NA,
        SpokenCue.SUCCESS_DA,
        SpokenCue.SUCCESS_GYA,
        SpokenCue.SUCCESS_GEO,
        SpokenCue.SUCCESS_GYEO,
        SpokenCue.SUCCESS_GO,
        SpokenCue.SUCCESS_GYO,
        SpokenCue.SUCCESS_GU,
        SpokenCue.SUCCESS_GYU,
        SpokenCue.SUCCESS_GEU,
        SpokenCue.SUCCESS_GI,
        SpokenCue.SUCCESS_RIEUL,
        SpokenCue.SUCCESS_MIEUM,
        SpokenCue.SUCCESS_BIEUP,
        SpokenCue.SUCCESS_SIOT,
        SpokenCue.SUCCESS_IEUNG,
        SpokenCue.SUCCESS_JIEUT,
        SpokenCue.SUCCESS_CHIEUT,
        SpokenCue.SUCCESS_KIEUK,
        SpokenCue.SUCCESS_TIEUT,
        SpokenCue.SUCCESS_PIEUP,
        SpokenCue.SUCCESS_HIEUH,
        SpokenCue.SUCCESS_YA,
        SpokenCue.SUCCESS_EO,
        SpokenCue.SUCCESS_YEO,
        SpokenCue.SUCCESS_O,
        SpokenCue.SUCCESS_YO,
        SpokenCue.SUCCESS_U,
        SpokenCue.SUCCESS_YU,
        SpokenCue.SUCCESS_EU,
        SpokenCue.SUCCESS_I,
        SpokenCue.SUCCESS_RA,
        SpokenCue.SUCCESS_MA,
        SpokenCue.SUCCESS_BA,
        SpokenCue.SUCCESS_SA,
        SpokenCue.SUCCESS_AH,
        SpokenCue.SUCCESS_JA,
        SpokenCue.SUCCESS_CHA,
        SpokenCue.SUCCESS_KA,
        SpokenCue.SUCCESS_TA,
        SpokenCue.SUCCESS_PA,
        SpokenCue.SUCCESS_HA,
        SpokenCue.SUCCESS_GAK,
        SpokenCue.SUCCESS_GAN,
        SpokenCue.SUCCESS_GAT,
        SpokenCue.SUCCESS_GAL,
        SpokenCue.SUCCESS_GAM,
        SpokenCue.SUCCESS_GAP,
        -> return null
        SpokenCue.INITIAL_GIEOK,
        SpokenCue.INITIAL_NIEUN,
        -> return 0
        SpokenCue.INITIAL_A,
        SpokenCue.INITIAL_AE,
        SpokenCue.INITIAL_YA,
        SpokenCue.INITIAL_EO,
        SpokenCue.INITIAL_YEO,
        SpokenCue.INITIAL_O,
        SpokenCue.INITIAL_YO,
        SpokenCue.INITIAL_U,
        SpokenCue.INITIAL_YU,
        SpokenCue.INITIAL_EU,
        SpokenCue.INITIAL_I,
        SpokenCue.INITIAL_DIGEUT,
        SpokenCue.INITIAL,
        SpokenCue.INITIAL_NA,
        SpokenCue.INITIAL_DA,
        SpokenCue.INITIAL_GYA,
        SpokenCue.INITIAL_GEO,
        SpokenCue.INITIAL_GYEO,
        SpokenCue.INITIAL_GO,
        SpokenCue.INITIAL_GYO,
        SpokenCue.INITIAL_GU,
        SpokenCue.INITIAL_GYU,
        SpokenCue.INITIAL_GEU,
        SpokenCue.INITIAL_GI,
        SpokenCue.INITIAL_RIEUL,
        SpokenCue.INITIAL_MIEUM,
        SpokenCue.INITIAL_BIEUP,
        SpokenCue.INITIAL_SIOT,
        SpokenCue.INITIAL_IEUNG,
        SpokenCue.INITIAL_JIEUT,
        SpokenCue.INITIAL_CHIEUT,
        SpokenCue.INITIAL_KIEUK,
        SpokenCue.INITIAL_TIEUT,
        SpokenCue.INITIAL_PIEUP,
        SpokenCue.INITIAL_HIEUH,
        SpokenCue.INITIAL_RA,
        SpokenCue.INITIAL_MA,
        SpokenCue.INITIAL_BA,
        SpokenCue.INITIAL_SA,
        SpokenCue.INITIAL_AH,
        SpokenCue.INITIAL_JA,
        SpokenCue.INITIAL_CHA,
        SpokenCue.INITIAL_KA,
        SpokenCue.INITIAL_TA,
        SpokenCue.INITIAL_PA,
        SpokenCue.INITIAL_HA,
        SpokenCue.INITIAL_GAK,
        SpokenCue.INITIAL_GAN,
        SpokenCue.INITIAL_GAT,
        SpokenCue.INITIAL_GAL,
        SpokenCue.INITIAL_GAM,
        SpokenCue.INITIAL_GAP,
        -> Unit
    }

    val strokeStarts = buildList {
        add(0)
        var boundary = utterance.indexOf(". ")
        while (boundary >= 0) {
            add(boundary + 2)
            boundary = utterance.indexOf(". ", boundary + 2)
        }
    }
    return strokeStarts.indexOfLast { characterStart >= it }.coerceAtLeast(0)
}
