#!/usr/bin/env bash

# LimDo CLI 루프 공개 설정이다. 비밀키나 인증 정보를 넣지 않는다.
CODEX_LOOP_MODEL="${CODEX_LOOP_MODEL:-}"
CODEX_LOOP_PAUSE_SECONDS="${CODEX_LOOP_PAUSE_SECONDS:-2}"
CODEX_LOOP_MAX_SESSIONS="${CODEX_LOOP_MAX_SESSIONS:-0}"
CODEX_LOOP_MAX_PROCESS_FAILURES="${CODEX_LOOP_MAX_PROCESS_FAILURES:-3}"
CODEX_LOOP_SANDBOX="${CODEX_LOOP_SANDBOX:-danger-full-access}"

export CODEX_LOOP_MODEL
export CODEX_LOOP_PAUSE_SECONDS
export CODEX_LOOP_MAX_SESSIONS
export CODEX_LOOP_MAX_PROCESS_FAILURES
export CODEX_LOOP_SANDBOX
