package com.limdo.hangul

internal data class LessonSpec(
    val id: LessonId,
    val stage: CurriculumStage,
    val glyph: String,
    val strokeCount: Int,
    val initialCue: SpokenCue,
    val successCue: SpokenCue,
    val strokeDirections: List<StrokeDirection>,
)

internal enum class LessonId {
    GIEOK, NIEUN, DIGEUT, RIEUL, MIEUM, BIEUP, SIOT, IEUNG, JIEUT, CHIEUT, KIEUK, TIEUT,
    PIEUP, HIEUH,
    A, AE, YA, EO, YEO, O, YO, U, YU, EU, I, GA, NA, DA, RA, MA, BA, SA, AH, JA, CHA, KA, TA,
    PA, HA, GYA, GEO, GYEO, GO, GYO, GU, GYU, GEU, GI, NEO, NYEO, NO, NYO, NU, NYU, NEU, NI, DEO, DYEO, DO, DYO, DU, DYU, DEU, DI, GAK, GAN, GAT, GAL, GAM, GAP,
}

internal enum class StrokeDirection { RIGHT, LEFT, UP, DOWN }

internal enum class CurriculumStage {
    PENCIL_PREPARATION,
    CONSONANTS,
    VOWELS,
    SYLLABLE_STRUCTURE,
    OPEN_SYLLABLES,
    FINAL_CONSONANTS,
    DOUBLE_FINAL_CONSONANTS,
}

internal object KoreanCurriculum {
    val educationFlow = CurriculumStage.entries

    val lessons = listOf(
        LessonSpec(
            id = LessonId.GIEOK,
            stage = CurriculumStage.CONSONANTS,
            glyph = "ㄱ",
            strokeCount = 1,
            initialCue = SpokenCue.INITIAL_GIEOK,
            successCue = SpokenCue.SUCCESS_GIEOK,
            strokeDirections = listOf(StrokeDirection.RIGHT),
        ),
        LessonSpec(
            id = LessonId.NIEUN,
            stage = CurriculumStage.CONSONANTS,
            glyph = "ㄴ",
            strokeCount = 1,
            initialCue = SpokenCue.INITIAL_NIEUN,
            successCue = SpokenCue.SUCCESS_NIEUN,
            strokeDirections = listOf(StrokeDirection.DOWN),
        ),
        LessonSpec(
            id = LessonId.DIGEUT,
            stage = CurriculumStage.CONSONANTS,
            glyph = "ㄷ",
            strokeCount = 2,
            initialCue = SpokenCue.INITIAL_DIGEUT,
            successCue = SpokenCue.SUCCESS_DIGEUT,
            strokeDirections = listOf(StrokeDirection.RIGHT, StrokeDirection.DOWN),
        ),
        LessonSpec(
            id = LessonId.RIEUL,
            stage = CurriculumStage.CONSONANTS,
            glyph = "ㄹ",
            strokeCount = 3,
            initialCue = SpokenCue.INITIAL_RIEUL,
            successCue = SpokenCue.SUCCESS_RIEUL,
            strokeDirections = listOf(StrokeDirection.RIGHT, StrokeDirection.RIGHT, StrokeDirection.DOWN),
        ),
        LessonSpec(
            id = LessonId.MIEUM,
            stage = CurriculumStage.CONSONANTS,
            glyph = "ㅁ",
            strokeCount = 3,
            initialCue = SpokenCue.INITIAL_MIEUM,
            successCue = SpokenCue.SUCCESS_MIEUM,
            strokeDirections = listOf(StrokeDirection.DOWN, StrokeDirection.RIGHT, StrokeDirection.RIGHT),
        ),
        LessonSpec(
            id = LessonId.BIEUP,
            stage = CurriculumStage.CONSONANTS,
            glyph = "ㅂ",
            strokeCount = 4,
            initialCue = SpokenCue.INITIAL_BIEUP,
            successCue = SpokenCue.SUCCESS_BIEUP,
            strokeDirections = listOf(
                StrokeDirection.DOWN,
                StrokeDirection.DOWN,
                StrokeDirection.RIGHT,
                StrokeDirection.RIGHT,
            ),
        ),
        LessonSpec(
            id = LessonId.SIOT,
            stage = CurriculumStage.CONSONANTS,
            glyph = "ㅅ",
            strokeCount = 2,
            initialCue = SpokenCue.INITIAL_SIOT,
            successCue = SpokenCue.SUCCESS_SIOT,
            strokeDirections = listOf(StrokeDirection.DOWN, StrokeDirection.DOWN),
        ),
        LessonSpec(
            id = LessonId.IEUNG,
            stage = CurriculumStage.CONSONANTS,
            glyph = "ㅇ",
            strokeCount = 1,
            initialCue = SpokenCue.INITIAL_IEUNG,
            successCue = SpokenCue.SUCCESS_IEUNG,
            strokeDirections = listOf(StrokeDirection.LEFT),
        ),
        LessonSpec(
            id = LessonId.JIEUT,
            stage = CurriculumStage.CONSONANTS,
            glyph = "ㅈ",
            strokeCount = 2,
            initialCue = SpokenCue.INITIAL_JIEUT,
            successCue = SpokenCue.SUCCESS_JIEUT,
            strokeDirections = listOf(StrokeDirection.RIGHT, StrokeDirection.DOWN),
        ),
        LessonSpec(
            id = LessonId.CHIEUT,
            stage = CurriculumStage.CONSONANTS,
            glyph = "ㅊ",
            strokeCount = 3,
            initialCue = SpokenCue.INITIAL_CHIEUT,
            successCue = SpokenCue.SUCCESS_CHIEUT,
            strokeDirections = listOf(
                StrokeDirection.RIGHT,
                StrokeDirection.RIGHT,
                StrokeDirection.DOWN,
            ),
        ),
        LessonSpec(
            id = LessonId.KIEUK,
            stage = CurriculumStage.CONSONANTS,
            glyph = "ㅋ",
            strokeCount = 2,
            initialCue = SpokenCue.INITIAL_KIEUK,
            successCue = SpokenCue.SUCCESS_KIEUK,
            strokeDirections = listOf(StrokeDirection.RIGHT, StrokeDirection.RIGHT),
        ),
        LessonSpec(
            id = LessonId.TIEUT,
            stage = CurriculumStage.CONSONANTS,
            glyph = "ㅌ",
            strokeCount = 3,
            initialCue = SpokenCue.INITIAL_TIEUT,
            successCue = SpokenCue.SUCCESS_TIEUT,
            strokeDirections = listOf(StrokeDirection.RIGHT, StrokeDirection.RIGHT, StrokeDirection.DOWN),
        ),
        LessonSpec(
            id = LessonId.PIEUP,
            stage = CurriculumStage.CONSONANTS,
            glyph = "ㅍ",
            strokeCount = 4,
            initialCue = SpokenCue.INITIAL_PIEUP,
            successCue = SpokenCue.SUCCESS_PIEUP,
            strokeDirections = listOf(
                StrokeDirection.RIGHT,
                StrokeDirection.DOWN,
                StrokeDirection.DOWN,
                StrokeDirection.RIGHT,
            ),
        ),
        LessonSpec(
            id = LessonId.HIEUH,
            stage = CurriculumStage.CONSONANTS,
            glyph = "ㅎ",
            strokeCount = 3,
            initialCue = SpokenCue.INITIAL_HIEUH,
            successCue = SpokenCue.SUCCESS_HIEUH,
            strokeDirections = listOf(StrokeDirection.RIGHT, StrokeDirection.RIGHT, StrokeDirection.LEFT),
        ),
        LessonSpec(
            id = LessonId.A,
            stage = CurriculumStage.VOWELS,
            glyph = "ㅏ",
            strokeCount = 2,
            initialCue = SpokenCue.INITIAL_A,
            successCue = SpokenCue.SUCCESS_A,
            strokeDirections = listOf(StrokeDirection.DOWN, StrokeDirection.RIGHT),
        ),
        LessonSpec(
            id = LessonId.AE,
            stage = CurriculumStage.VOWELS,
            glyph = "ㅐ",
            strokeCount = 3,
            initialCue = SpokenCue.INITIAL_AE,
            successCue = SpokenCue.SUCCESS_AE,
            strokeDirections = listOf(StrokeDirection.DOWN, StrokeDirection.RIGHT, StrokeDirection.DOWN),
        ),
        LessonSpec(
            id = LessonId.YA,
            stage = CurriculumStage.VOWELS,
            glyph = "ㅑ",
            strokeCount = 3,
            initialCue = SpokenCue.INITIAL_YA,
            successCue = SpokenCue.SUCCESS_YA,
            strokeDirections = listOf(StrokeDirection.DOWN, StrokeDirection.RIGHT, StrokeDirection.RIGHT),
        ),
        LessonSpec(
            id = LessonId.EO,
            stage = CurriculumStage.VOWELS,
            glyph = "ㅓ",
            strokeCount = 2,
            initialCue = SpokenCue.INITIAL_EO,
            successCue = SpokenCue.SUCCESS_EO,
            strokeDirections = listOf(StrokeDirection.RIGHT, StrokeDirection.DOWN),
        ),
        LessonSpec(
            id = LessonId.YEO,
            stage = CurriculumStage.VOWELS,
            glyph = "ㅕ",
            strokeCount = 3,
            initialCue = SpokenCue.INITIAL_YEO,
            successCue = SpokenCue.SUCCESS_YEO,
            strokeDirections = listOf(StrokeDirection.RIGHT, StrokeDirection.RIGHT, StrokeDirection.DOWN),
        ),
        LessonSpec(
            id = LessonId.O,
            stage = CurriculumStage.VOWELS,
            glyph = "ㅗ",
            strokeCount = 2,
            initialCue = SpokenCue.INITIAL_O,
            successCue = SpokenCue.SUCCESS_O,
            strokeDirections = listOf(StrokeDirection.DOWN, StrokeDirection.RIGHT),
        ),
        LessonSpec(
            id = LessonId.YO,
            stage = CurriculumStage.VOWELS,
            glyph = "ㅛ",
            strokeCount = 3,
            initialCue = SpokenCue.INITIAL_YO,
            successCue = SpokenCue.SUCCESS_YO,
            strokeDirections = listOf(StrokeDirection.DOWN, StrokeDirection.DOWN, StrokeDirection.RIGHT),
        ),
        LessonSpec(
            id = LessonId.U,
            stage = CurriculumStage.VOWELS,
            glyph = "ㅜ",
            strokeCount = 2,
            initialCue = SpokenCue.INITIAL_U,
            successCue = SpokenCue.SUCCESS_U,
            strokeDirections = listOf(StrokeDirection.RIGHT, StrokeDirection.DOWN),
        ),
        LessonSpec(
            id = LessonId.YU,
            stage = CurriculumStage.VOWELS,
            glyph = "ㅠ",
            strokeCount = 3,
            initialCue = SpokenCue.INITIAL_YU,
            successCue = SpokenCue.SUCCESS_YU,
            strokeDirections = listOf(StrokeDirection.RIGHT, StrokeDirection.DOWN, StrokeDirection.DOWN),
        ),
        LessonSpec(
            id = LessonId.EU,
            stage = CurriculumStage.VOWELS,
            glyph = "ㅡ",
            strokeCount = 1,
            initialCue = SpokenCue.INITIAL_EU,
            successCue = SpokenCue.SUCCESS_EU,
            strokeDirections = listOf(StrokeDirection.RIGHT),
        ),
        LessonSpec(
            id = LessonId.I,
            stage = CurriculumStage.VOWELS,
            glyph = "ㅣ",
            strokeCount = 1,
            initialCue = SpokenCue.INITIAL_I,
            successCue = SpokenCue.SUCCESS_I,
            strokeDirections = listOf(StrokeDirection.DOWN),
        ),
        LessonSpec(
            id = LessonId.GA,
            stage = CurriculumStage.SYLLABLE_STRUCTURE,
            glyph = "가",
            strokeCount = 3,
            initialCue = SpokenCue.INITIAL,
            successCue = SpokenCue.SUCCESS,
            strokeDirections = listOf(StrokeDirection.RIGHT, StrokeDirection.DOWN, StrokeDirection.RIGHT),
        ),
        LessonSpec(
            id = LessonId.NA,
            stage = CurriculumStage.SYLLABLE_STRUCTURE,
            glyph = "나",
            strokeCount = 3,
            initialCue = SpokenCue.INITIAL_NA,
            successCue = SpokenCue.SUCCESS_NA,
            strokeDirections = listOf(StrokeDirection.DOWN, StrokeDirection.DOWN, StrokeDirection.RIGHT),
        ),
        LessonSpec(
            id = LessonId.NEO,
            stage = CurriculumStage.SYLLABLE_STRUCTURE,
            glyph = "너",
            strokeCount = 3,
            initialCue = SpokenCue.INITIAL_NEO,
            successCue = SpokenCue.SUCCESS_NEO,
            strokeDirections = listOf(StrokeDirection.DOWN, StrokeDirection.DOWN, StrokeDirection.LEFT),
        ),
        LessonSpec(
            id = LessonId.NYEO,
            stage = CurriculumStage.SYLLABLE_STRUCTURE,
            glyph = "\uB140",
            strokeCount = 4,
            initialCue = SpokenCue.INITIAL_NYEO,
            successCue = SpokenCue.SUCCESS_NYEO,
            strokeDirections = listOf(StrokeDirection.DOWN, StrokeDirection.DOWN, StrokeDirection.LEFT, StrokeDirection.LEFT),
        ),
        LessonSpec(
            id = LessonId.NO,
            stage = CurriculumStage.SYLLABLE_STRUCTURE,
            glyph = "노",
            strokeCount = 3,
            initialCue = SpokenCue.INITIAL_NO,
            successCue = SpokenCue.SUCCESS_NO,
            strokeDirections = listOf(StrokeDirection.DOWN, StrokeDirection.RIGHT, StrokeDirection.UP),
        ),
        LessonSpec(
            id = LessonId.NYO,
            stage = CurriculumStage.SYLLABLE_STRUCTURE,
            glyph = "뇨",
            strokeCount = 4,
            initialCue = SpokenCue.INITIAL_NYO,
            successCue = SpokenCue.SUCCESS_NYO,
            strokeDirections = listOf(StrokeDirection.DOWN, StrokeDirection.RIGHT, StrokeDirection.UP, StrokeDirection.UP),
        ),
        LessonSpec(
            id = LessonId.NU,
            stage = CurriculumStage.SYLLABLE_STRUCTURE,
            glyph = "누",
            strokeCount = 3,
            initialCue = SpokenCue.INITIAL_NU,
            successCue = SpokenCue.SUCCESS_NU,
            strokeDirections = listOf(StrokeDirection.DOWN, StrokeDirection.RIGHT, StrokeDirection.DOWN),
        ),
        LessonSpec(
            id = LessonId.NYU,
            stage = CurriculumStage.SYLLABLE_STRUCTURE,
            glyph = "뉴",
            strokeCount = 4,
            initialCue = SpokenCue.INITIAL_NYU,
            successCue = SpokenCue.SUCCESS_NYU,
            strokeDirections = listOf(StrokeDirection.DOWN, StrokeDirection.RIGHT, StrokeDirection.DOWN, StrokeDirection.DOWN),
        ),
        LessonSpec(
            id = LessonId.NEU,
            stage = CurriculumStage.SYLLABLE_STRUCTURE,
            glyph = "느",
            strokeCount = 2,
            initialCue = SpokenCue.INITIAL_NEU,
            successCue = SpokenCue.SUCCESS_NEU,
            strokeDirections = listOf(StrokeDirection.DOWN, StrokeDirection.RIGHT),
        ),
        LessonSpec(
            id = LessonId.NI,
            stage = CurriculumStage.SYLLABLE_STRUCTURE,
            glyph = "니",
            strokeCount = 2,
            initialCue = SpokenCue.INITIAL_NI,
            successCue = SpokenCue.SUCCESS_NI,
            strokeDirections = listOf(StrokeDirection.DOWN, StrokeDirection.DOWN),
        ),
        LessonSpec(
            id = LessonId.DA,
            stage = CurriculumStage.SYLLABLE_STRUCTURE,
            glyph = "다",
            strokeCount = 4,
            initialCue = SpokenCue.INITIAL_DA,
            successCue = SpokenCue.SUCCESS_DA,
            strokeDirections = listOf(
                StrokeDirection.RIGHT,
                StrokeDirection.DOWN,
                StrokeDirection.DOWN,
                StrokeDirection.RIGHT,
            ),
        ),
        LessonSpec(
            id = LessonId.DEO,
            stage = CurriculumStage.SYLLABLE_STRUCTURE,
            glyph = "더",
            strokeCount = 4,
            initialCue = SpokenCue.INITIAL_DEO,
            successCue = SpokenCue.SUCCESS_DEO,
            strokeDirections = listOf(
                StrokeDirection.RIGHT,
                StrokeDirection.DOWN,
                StrokeDirection.DOWN,
                StrokeDirection.LEFT,
            ),
        ),
        LessonSpec(
            id = LessonId.DYEO,
            stage = CurriculumStage.SYLLABLE_STRUCTURE,
            glyph = "뎌",
            strokeCount = 5,
            initialCue = SpokenCue.INITIAL_DYEO,
            successCue = SpokenCue.SUCCESS_DYEO,
            strokeDirections = listOf(StrokeDirection.RIGHT, StrokeDirection.DOWN, StrokeDirection.DOWN, StrokeDirection.LEFT, StrokeDirection.LEFT),
        ),
        LessonSpec(
            id = LessonId.DO,
            stage = CurriculumStage.SYLLABLE_STRUCTURE,
            glyph = "도",
            strokeCount = 4,
            initialCue = SpokenCue.INITIAL_DO,
            successCue = SpokenCue.SUCCESS_DO,
            strokeDirections = listOf(StrokeDirection.RIGHT, StrokeDirection.DOWN, StrokeDirection.RIGHT, StrokeDirection.UP),
        ),
        LessonSpec(LessonId.DYO, CurriculumStage.SYLLABLE_STRUCTURE, "\uB434", 5, SpokenCue.INITIAL_DYO, SpokenCue.SUCCESS_DYO,
            listOf(StrokeDirection.RIGHT, StrokeDirection.DOWN, StrokeDirection.RIGHT, StrokeDirection.UP, StrokeDirection.UP)),
        LessonSpec(LessonId.DU, CurriculumStage.SYLLABLE_STRUCTURE, "두", 4, SpokenCue.INITIAL_DU, SpokenCue.SUCCESS_DU,
            listOf(StrokeDirection.RIGHT, StrokeDirection.DOWN, StrokeDirection.RIGHT, StrokeDirection.DOWN)),
        LessonSpec(LessonId.DYU, CurriculumStage.SYLLABLE_STRUCTURE, "듀", 5, SpokenCue.INITIAL_DYU, SpokenCue.SUCCESS_DYU,
            listOf(StrokeDirection.RIGHT, StrokeDirection.DOWN, StrokeDirection.RIGHT, StrokeDirection.DOWN, StrokeDirection.DOWN)),
        LessonSpec(LessonId.DEU, CurriculumStage.SYLLABLE_STRUCTURE, "드", 3, SpokenCue.INITIAL_DEU, SpokenCue.SUCCESS_DEU,
            listOf(StrokeDirection.RIGHT, StrokeDirection.DOWN, StrokeDirection.RIGHT)),
        LessonSpec(LessonId.DI, CurriculumStage.SYLLABLE_STRUCTURE, "디", 3, SpokenCue.INITIAL_DI, SpokenCue.SUCCESS_DI,
            listOf(StrokeDirection.RIGHT, StrokeDirection.DOWN, StrokeDirection.DOWN)),
        LessonSpec(LessonId.GYA, CurriculumStage.OPEN_SYLLABLES, "갸", 4, SpokenCue.INITIAL_GYA, SpokenCue.SUCCESS_GYA,
            listOf(StrokeDirection.RIGHT, StrokeDirection.DOWN, StrokeDirection.RIGHT, StrokeDirection.RIGHT)),
        LessonSpec(LessonId.GEO, CurriculumStage.OPEN_SYLLABLES, "거", 3, SpokenCue.INITIAL_GEO, SpokenCue.SUCCESS_GEO,
            listOf(StrokeDirection.RIGHT, StrokeDirection.DOWN, StrokeDirection.LEFT)),
        LessonSpec(LessonId.GYEO, CurriculumStage.OPEN_SYLLABLES, "겨", 4, SpokenCue.INITIAL_GYEO, SpokenCue.SUCCESS_GYEO,
            listOf(StrokeDirection.RIGHT, StrokeDirection.DOWN, StrokeDirection.LEFT, StrokeDirection.LEFT)),
        LessonSpec(LessonId.GO, CurriculumStage.OPEN_SYLLABLES, "고", 3, SpokenCue.INITIAL_GO, SpokenCue.SUCCESS_GO,
            listOf(StrokeDirection.RIGHT, StrokeDirection.RIGHT, StrokeDirection.UP)),
        LessonSpec(LessonId.GYO, CurriculumStage.OPEN_SYLLABLES, "교", 4, SpokenCue.INITIAL_GYO, SpokenCue.SUCCESS_GYO,
            listOf(StrokeDirection.RIGHT, StrokeDirection.RIGHT, StrokeDirection.UP, StrokeDirection.UP)),
        LessonSpec(LessonId.GU, CurriculumStage.OPEN_SYLLABLES, "구", 3, SpokenCue.INITIAL_GU, SpokenCue.SUCCESS_GU,
            listOf(StrokeDirection.RIGHT, StrokeDirection.RIGHT, StrokeDirection.DOWN)),
        LessonSpec(LessonId.GYU, CurriculumStage.OPEN_SYLLABLES, "규", 4, SpokenCue.INITIAL_GYU, SpokenCue.SUCCESS_GYU,
            listOf(StrokeDirection.RIGHT, StrokeDirection.RIGHT, StrokeDirection.DOWN, StrokeDirection.DOWN)),
        LessonSpec(LessonId.GEU, CurriculumStage.OPEN_SYLLABLES, "그", 2, SpokenCue.INITIAL_GEU, SpokenCue.SUCCESS_GEU,
            listOf(StrokeDirection.RIGHT, StrokeDirection.RIGHT)),
        LessonSpec(LessonId.GI, CurriculumStage.OPEN_SYLLABLES, "기", 2, SpokenCue.INITIAL_GI, SpokenCue.SUCCESS_GI,
            listOf(StrokeDirection.RIGHT, StrokeDirection.DOWN)),
        LessonSpec(
            id = LessonId.RA,
            stage = CurriculumStage.OPEN_SYLLABLES,
            glyph = "라",
            strokeCount = 5,
            initialCue = SpokenCue.INITIAL_RA,
            successCue = SpokenCue.SUCCESS_RA,
            strokeDirections = listOf(
                StrokeDirection.RIGHT,
                StrokeDirection.RIGHT,
                StrokeDirection.DOWN,
                StrokeDirection.DOWN,
                StrokeDirection.RIGHT,
            ),
        ),
        LessonSpec(
            id = LessonId.MA,
            stage = CurriculumStage.OPEN_SYLLABLES,
            glyph = "마",
            strokeCount = 5,
            initialCue = SpokenCue.INITIAL_MA,
            successCue = SpokenCue.SUCCESS_MA,
            strokeDirections = listOf(
                StrokeDirection.DOWN,
                StrokeDirection.RIGHT,
                StrokeDirection.RIGHT,
                StrokeDirection.DOWN,
                StrokeDirection.RIGHT,
            ),
        ),
        LessonSpec(
            id = LessonId.BA,
            stage = CurriculumStage.OPEN_SYLLABLES,
            glyph = "바",
            strokeCount = 6,
            initialCue = SpokenCue.INITIAL_BA,
            successCue = SpokenCue.SUCCESS_BA,
            strokeDirections = listOf(
                StrokeDirection.DOWN,
                StrokeDirection.DOWN,
                StrokeDirection.RIGHT,
                StrokeDirection.RIGHT,
                StrokeDirection.DOWN,
                StrokeDirection.RIGHT,
            ),
        ),
        LessonSpec(
            id = LessonId.SA,
            stage = CurriculumStage.OPEN_SYLLABLES,
            glyph = "사",
            strokeCount = 4,
            initialCue = SpokenCue.INITIAL_SA,
            successCue = SpokenCue.SUCCESS_SA,
            strokeDirections = listOf(
                StrokeDirection.DOWN,
                StrokeDirection.DOWN,
                StrokeDirection.DOWN,
                StrokeDirection.RIGHT,
            ),
        ),
        LessonSpec(
            id = LessonId.AH,
            stage = CurriculumStage.OPEN_SYLLABLES,
            glyph = "아",
            strokeCount = 3,
            initialCue = SpokenCue.INITIAL_AH,
            successCue = SpokenCue.SUCCESS_AH,
            strokeDirections = listOf(
                StrokeDirection.LEFT,
                StrokeDirection.DOWN,
                StrokeDirection.RIGHT,
            ),
        ),
        LessonSpec(
            id = LessonId.JA,
            stage = CurriculumStage.OPEN_SYLLABLES,
            glyph = "자",
            strokeCount = 4,
            initialCue = SpokenCue.INITIAL_JA,
            successCue = SpokenCue.SUCCESS_JA,
            strokeDirections = listOf(
                StrokeDirection.RIGHT,
                StrokeDirection.DOWN,
                StrokeDirection.DOWN,
                StrokeDirection.RIGHT,
            ),
        ),
        LessonSpec(
            id = LessonId.CHA,
            stage = CurriculumStage.OPEN_SYLLABLES,
            glyph = "차",
            strokeCount = 5,
            initialCue = SpokenCue.INITIAL_CHA,
            successCue = SpokenCue.SUCCESS_CHA,
            strokeDirections = listOf(
                StrokeDirection.RIGHT,
                StrokeDirection.RIGHT,
                StrokeDirection.DOWN,
                StrokeDirection.DOWN,
                StrokeDirection.RIGHT,
            ),
        ),
        LessonSpec(
            id = LessonId.KA,
            stage = CurriculumStage.OPEN_SYLLABLES,
            glyph = "카",
            strokeCount = 4,
            initialCue = SpokenCue.INITIAL_KA,
            successCue = SpokenCue.SUCCESS_KA,
            strokeDirections = listOf(
                StrokeDirection.RIGHT,
                StrokeDirection.RIGHT,
                StrokeDirection.DOWN,
                StrokeDirection.RIGHT,
            ),
        ),
        LessonSpec(
            id = LessonId.TA,
            stage = CurriculumStage.OPEN_SYLLABLES,
            glyph = "타",
            strokeCount = 5,
            initialCue = SpokenCue.INITIAL_TA,
            successCue = SpokenCue.SUCCESS_TA,
            strokeDirections = listOf(
                StrokeDirection.RIGHT,
                StrokeDirection.RIGHT,
                StrokeDirection.DOWN,
                StrokeDirection.DOWN,
                StrokeDirection.RIGHT,
            ),
        ),
        LessonSpec(
            id = LessonId.PA,
            stage = CurriculumStage.OPEN_SYLLABLES,
            glyph = "파",
            strokeCount = 6,
            initialCue = SpokenCue.INITIAL_PA,
            successCue = SpokenCue.SUCCESS_PA,
            strokeDirections = listOf(
                StrokeDirection.RIGHT,
                StrokeDirection.DOWN,
                StrokeDirection.DOWN,
                StrokeDirection.RIGHT,
                StrokeDirection.DOWN,
                StrokeDirection.RIGHT,
            ),
        ),
        LessonSpec(
            id = LessonId.HA,
            stage = CurriculumStage.OPEN_SYLLABLES,
            glyph = "하",
            strokeCount = 5,
            initialCue = SpokenCue.INITIAL_HA,
            successCue = SpokenCue.SUCCESS_HA,
            strokeDirections = listOf(
                StrokeDirection.RIGHT,
                StrokeDirection.RIGHT,
                StrokeDirection.LEFT,
                StrokeDirection.DOWN,
                StrokeDirection.RIGHT,
            ),
        ),
        LessonSpec(
            id = LessonId.GAK,
            stage = CurriculumStage.FINAL_CONSONANTS,
            glyph = "각",
            strokeCount = 4,
            initialCue = SpokenCue.INITIAL_GAK,
            successCue = SpokenCue.SUCCESS_GAK,
            strokeDirections = listOf(
                StrokeDirection.RIGHT,
                StrokeDirection.DOWN,
                StrokeDirection.RIGHT,
                StrokeDirection.RIGHT,
            ),
        ),
        LessonSpec(
            id = LessonId.GAN,
            stage = CurriculumStage.FINAL_CONSONANTS,
            glyph = "간",
            strokeCount = 4,
            initialCue = SpokenCue.INITIAL_GAN,
            successCue = SpokenCue.SUCCESS_GAN,
            strokeDirections = listOf(
                StrokeDirection.RIGHT,
                StrokeDirection.DOWN,
                StrokeDirection.RIGHT,
                StrokeDirection.DOWN,
            ),
        ),
        LessonSpec(
            id = LessonId.GAT,
            stage = CurriculumStage.FINAL_CONSONANTS,
            glyph = "갇",
            strokeCount = 5,
            initialCue = SpokenCue.INITIAL_GAT,
            successCue = SpokenCue.SUCCESS_GAT,
            strokeDirections = listOf(
                StrokeDirection.RIGHT,
                StrokeDirection.DOWN,
                StrokeDirection.RIGHT,
                StrokeDirection.RIGHT,
                StrokeDirection.DOWN,
            ),
        ),
        LessonSpec(
            id = LessonId.GAL,
            stage = CurriculumStage.FINAL_CONSONANTS,
            glyph = "갈",
            strokeCount = 6,
            initialCue = SpokenCue.INITIAL_GAL,
            successCue = SpokenCue.SUCCESS_GAL,
            strokeDirections = listOf(
                StrokeDirection.RIGHT,
                StrokeDirection.DOWN,
                StrokeDirection.RIGHT,
                StrokeDirection.RIGHT,
                StrokeDirection.LEFT,
                StrokeDirection.RIGHT,
            ),
        ),
        LessonSpec(
            id = LessonId.GAM,
            stage = CurriculumStage.FINAL_CONSONANTS,
            glyph = "감",
            strokeCount = 6,
            initialCue = SpokenCue.INITIAL_GAM,
            successCue = SpokenCue.SUCCESS_GAM,
            strokeDirections = listOf(
                StrokeDirection.RIGHT,
                StrokeDirection.DOWN,
                StrokeDirection.RIGHT,
                StrokeDirection.DOWN,
                StrokeDirection.RIGHT,
                StrokeDirection.RIGHT,
            ),
        ),
        LessonSpec(
            id = LessonId.GAP,
            stage = CurriculumStage.FINAL_CONSONANTS,
            glyph = "갑",
            strokeCount = 7,
            initialCue = SpokenCue.INITIAL_GAP,
            successCue = SpokenCue.SUCCESS_GAP,
            strokeDirections = listOf(
                StrokeDirection.RIGHT,
                StrokeDirection.DOWN,
                StrokeDirection.RIGHT,
                StrokeDirection.DOWN,
                StrokeDirection.DOWN,
                StrokeDirection.RIGHT,
                StrokeDirection.RIGHT,
            ),
        ),
    )

    fun nextIndex(currentIndex: Int): Int = (currentIndex + 1) % lessons.size
}

internal val GieokLesson = KoreanCurriculum.lessons.first { it.id == LessonId.GIEOK }
internal val NieunLesson = KoreanCurriculum.lessons.first { it.id == LessonId.NIEUN }
internal val DigeutLesson = KoreanCurriculum.lessons.first { it.id == LessonId.DIGEUT }
internal val RieulLesson = KoreanCurriculum.lessons.first { it.id == LessonId.RIEUL }
internal val MieumLesson = KoreanCurriculum.lessons.first { it.id == LessonId.MIEUM }
internal val BieupLesson = KoreanCurriculum.lessons.first { it.id == LessonId.BIEUP }
internal val SiotLesson = KoreanCurriculum.lessons.first { it.id == LessonId.SIOT }
internal val IeungLesson = KoreanCurriculum.lessons.first { it.id == LessonId.IEUNG }
internal val JieutLesson = KoreanCurriculum.lessons.first { it.id == LessonId.JIEUT }
internal val ChieutLesson = KoreanCurriculum.lessons.first { it.id == LessonId.CHIEUT }
internal val KieukLesson = KoreanCurriculum.lessons.first { it.id == LessonId.KIEUK }
internal val TieutLesson = KoreanCurriculum.lessons.first { it.id == LessonId.TIEUT }
internal val PieupLesson = KoreanCurriculum.lessons.first { it.id == LessonId.PIEUP }
internal val HieuhLesson = KoreanCurriculum.lessons.first { it.id == LessonId.HIEUH }
internal val ALesson = KoreanCurriculum.lessons.first { it.id == LessonId.A }
internal val AeLesson = KoreanCurriculum.lessons.first { it.id == LessonId.AE }
internal val YaLesson = KoreanCurriculum.lessons.first { it.id == LessonId.YA }
internal val EoLesson = KoreanCurriculum.lessons.first { it.id == LessonId.EO }
internal val YeoLesson = KoreanCurriculum.lessons.first { it.id == LessonId.YEO }
internal val OLesson = KoreanCurriculum.lessons.first { it.id == LessonId.O }
internal val YoLesson = KoreanCurriculum.lessons.first { it.id == LessonId.YO }
internal val ULesson = KoreanCurriculum.lessons.first { it.id == LessonId.U }
internal val YuLesson = KoreanCurriculum.lessons.first { it.id == LessonId.YU }
internal val EuLesson = KoreanCurriculum.lessons.first { it.id == LessonId.EU }
internal val ILesson = KoreanCurriculum.lessons.first { it.id == LessonId.I }
internal val GaLesson = KoreanCurriculum.lessons.first { it.id == LessonId.GA }
internal val NaLesson = KoreanCurriculum.lessons.first { it.id == LessonId.NA }
internal val DaLesson = KoreanCurriculum.lessons.first { it.id == LessonId.DA }
internal val GyaLesson = KoreanCurriculum.lessons.first { it.id == LessonId.GYA }
internal val RaLesson = KoreanCurriculum.lessons.first { it.id == LessonId.RA }
internal val MaLesson = KoreanCurriculum.lessons.first { it.id == LessonId.MA }
internal val BaLesson = KoreanCurriculum.lessons.first { it.id == LessonId.BA }
internal val SaLesson = KoreanCurriculum.lessons.first { it.id == LessonId.SA }
internal val AhLesson = KoreanCurriculum.lessons.first { it.id == LessonId.AH }
internal val JaLesson = KoreanCurriculum.lessons.first { it.id == LessonId.JA }
internal val ChaLesson = KoreanCurriculum.lessons.first { it.id == LessonId.CHA }
internal val KaLesson = KoreanCurriculum.lessons.first { it.id == LessonId.KA }
internal val TaLesson = KoreanCurriculum.lessons.first { it.id == LessonId.TA }
internal val PaLesson = KoreanCurriculum.lessons.first { it.id == LessonId.PA }
internal val HaLesson = KoreanCurriculum.lessons.first { it.id == LessonId.HA }
internal val GakLesson = KoreanCurriculum.lessons.first { it.id == LessonId.GAK }
internal val GanLesson = KoreanCurriculum.lessons.first { it.id == LessonId.GAN }
internal val GatLesson = KoreanCurriculum.lessons.first { it.id == LessonId.GAT }
internal val GalLesson = KoreanCurriculum.lessons.first { it.id == LessonId.GAL }
internal val GamLesson = KoreanCurriculum.lessons.first { it.id == LessonId.GAM }
internal val GapLesson = KoreanCurriculum.lessons.first { it.id == LessonId.GAP }
